Q1. Write a python program which searches all the product under a particular product vertical

In [49]:
import pandas as pd 
import numpy as np
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import warnings
warnings.filterwarnings('ignore')

In [59]:
driver = webdriver.Chrome('/users/pratiksingh/Downloads/chromedriver')

In [60]:
driver.get('https://www.amazon.in/')

In [61]:
search = input("Enter product:")

Enter product:airpods

In [62]:
search_bar = driver.find_element_by_id("twotabsearchtextbox")
search_bar.clear()
search_bar.send_keys(search)                                  
search_button = driver.find_element_by_xpath('//span[@id="nav-search-submit-text"]')
search_button.click()

Q2.In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a data frame and csv. In case if any product vertical has less than 3 pages in search results then scrape all the products available under that product vertical. Details to be scraped are: "Brand Name", "Name of the Product", "Rating", "No. of Ratings", "Price", "Return/Exchange", "Expected Delivery", "Availability", "Other Details" and “Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“

In [63]:
Brand_Name = []
Product_Name = []
Rating = []
No_of_Ratings = []
Price = []
Return_Exchange = []
Expected_Delivery = []
Availability = []
Other_Details = []
Product_URL = []

In [64]:
urls=[i.get_attribute("href")for i in driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")]

In [65]:
urls=[i.get_attribute("href")for i in driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")]

for url in urls[0:100]:
    
        Product_URL.append(url)
        driver.get(url)        
        
        #for scrapping brand names
        b=driver.find_elements_by_xpath("//a[@id='bylineInfo']")
        for i in b:
            if i.text is None :
                Brand_Name.append('----') 
            else:
                Brand_Name.append(i.text)
        
        
        #scraping Product Names
        pn=driver.find_elements_by_xpath("//h1[@id='title']")
        for i in b:
            if i.text is None :
                Product_Name.append('----') 
            else:
                Product_Name.append(i.text)
                
        
        # scraping Rating
        r=driver.find_elements_by_xpath("//span[@data-hook='rating-out-of-text']")
        for i in r:
            if i.text is None :
                Rating.append('----') 
            else:
                Rating.append(i.text)

    
        # scraping No_of_Ratings
        nr=driver.find_elements_by_xpath("//span[@id='acrCustomerReviewText']")
        for i in nr:
            if i.text is None :
                No_of_Ratings.append('----') 
            else:
                No_of_Ratings.append(i.text)
        

        # scraping Price
        pr=driver.find_elements_by_xpath("//span[@id='priceblock_ourprice']")
        for i in nr:
            if i.text is None :
                Price.append('----') 
            else:
                Price.append(i.text)

        
        # scraping Expected Delivery
        ed = driver.find_elements_by_xpath("//div[@id='dynamicDeliveryMessage_feature_div']")
        for i in ed:
            if i.text is None :
                Expected_Delivery.append('----') 
            else:
                Expected_Delivery.append(i.text)

        
        # scraping Return/Exchange
        re = driver.find_elements_by_xpath("//a[@id='productSupportAndReturnPolicy-return-policy-anchor-text']")
        for i in re:
            if i.text is None :
                Return_Exchange.append('----') 
            else:
                Return_Exchange.append(i.text) 
        Return_Exchange[0:1]        
        
        # scraping Availability
        a=driver.find_elements_by_xpath("//div[@id='availability']/span")
        for i in a:
            if i.text is None :
                Availability.append('----') 
            else:
                Availability.append(i.text)

    
        # scraping other details
        od=driver.find_elements_by_xpath("//span[@id='price-shipping-message']")
        for i in a:
            if i.text is None :
                Other_Details.append('----') 
            else:
                Other_Details.append(i.text)

In [67]:
print(len(Brand_Name))
print(len(Product_Name))
print(len(Rating))
print(len(No_of_Ratings))
print(len(Price))
print(len(Return_Exchange))
print(len(Expected_Delivery))
print(len(Availability))
print(len(Other_Details))
print(len(Product_URL))

18
18
18
32
32
4
18
18
18
18

In [68]:
import pandas as pd
table=pd.DataFrame({})

table['Brand Name']=Brand_Name[:3]
table['Product Name']=Product_Name[:3]
table['Return/Exchane']=Return_Exchange[:3]
table['No of Ratings']=No_of_Ratings[:3]
table['Rating']=Rating[:3]
table['Price']=Price[:3]
table['Expected Delivery']=Expected_Delivery[:3]
table['Availability']=Availability[:3]
table['Other Details']=Other_Details[:3]
table['Product URL']=Product_URL[:3]

In [69]:
table

,Brand Name,Product Name,Return/Exchane,No of Ratings,Rating,Price,Expected Delivery,Availability,Other Details,Product URL
0,Visit the Apple Store,Visit the Apple Store,10-day replacement only,"9,455 ratings",4.5 out of 5,"9,455 ratings",,In stock.,In stock.,https://www.amazon.in/gp/slredirect/picassoRed...
1,Visit the Apple Store,Visit the Apple Store,10-day replacement only,"12,309 ratings",4.5 out of 5,"12,309 ratings",,In stock.,In stock.,https://www.amazon.in/gp/slredirect/picassoRed...
2,Visit the boAt Store,Visit the boAt Store,10-day replacement only,"43,402 ratings",3.9 out of 5,"43,402 ratings",,In stock.,In stock.,https://www.amazon.in/boAt-Airdopes-141-Wirele...

In [70]:
driver.close()

Q3.Write a python program to access the search bar and search button on images.google.com and scrape 100 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’

In [74]:
driver = webdriver.Chrome('/users/pratiksingh/Downloads/chromedriver')

In [75]:
driver.get('https://images.google.com/?gws_rd=ssl')

In [76]:
search_bar = driver.find_element_by_xpath('//input[@class="gLFyf gsfi"]')
search_bar.clear()
search_bar.send_keys('fruits')                                  
search_button = driver.find_element_by_xpath('//span[@class="z1asCe MZy1Rb"]')
search_button.click()

In [78]:
urls = driver.find_elements_by_xpath("//a[@class='wXeWr islib nfEiy mM5pbd']")

for urls in urls[0:100]:
    
        driver.find_element_by_xpath("//div[@class='bRMDJf islir']").click()        

        

        print(urls.get_attribute("href"))

same as cars and machine learning

Q4.Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Display Resolution”, “Processor”, “Processor Cores”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [85]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait 
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import urllib
import os

In [90]:
# Requesting Chrome driver to access the link:
driver = webdriver.Chrome('/users/pratiksingh/Downloads/chromedriver')
driver.maximize_window()
driver.get("https://www.flipkart.com/")

In [91]:
### scrapping search bar:-
search_bar = driver.find_element_by_xpath("//input[@class='_3704LK']")
search_bar.send_keys("Oneplus Nord  pixel 4A")

In [92]:
### Scrapping search button:-
search_button = driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_button.click()

In [93]:
Product_URL =[]

### Scrapping Url:

url = driver.find_elements_by_xpath("//a[@class='_1fQZEK']")
for i in url:
        Product_URL.append(i.get_attribute("href"))
        
        
time.sleep(2)   

print(len(Product_URL))

14

In [94]:
### Making Empty Lists:
Brand =[]
Phone_Name =[]
Colour =[]
Rom =[]
Primary_Camera =[]
Display_Size = []
Battery_Capacity =[]
Price =[]

for i in Product_URL:
    driver.get(i)
    time.sleep(5)
    ## Fetching Product Name:
    try:
        brd = driver.find_element_by_xpath("//span[@class='B_NuCI']")
        Brand.append(brd.text)
    except:
        Brand.append("-")
        
    ## Fetching price:
    try:
        pp = driver.find_element_by_xpath("//div[@class='_30jeq3 _16Jk6d']")
        Price.append(pp.text) 
    except:
        Price.append("-")
    ## Fetching  Colour:
    try:
        col = driver.find_element_by_xpath("//td[@class='URwL2w col col-9-12']/li")
        Colour.append(col.text)
    except:
        Colour.append("-")
    ## Fetching RAM/ROM details:
    try:
        #rom = driver.find_element_by_xpath("//div[@class = '_2418kt']/ul/li[1]")
        rom = driver.find_element_by_xpath("//div[@class='_2418kt']/ul/li[@class='_21Ahn-'][1]")
        Rom.append(rom.text)
            
                
    except:
        Rom.append("-")
        
    ## Fetching Display Size:-
    try:
        size = driver.find_element_by_xpath("//div[@class='_2418kt']/ul/li[@class='_21Ahn-'][2]")
        Display_Size.append(size.text)
        
    except:
        Display_Size.append("-")
    ## Fetching Primary/Secondary Camera :-
    try:
        pc = driver.find_element_by_xpath("//div[@class='_2418kt']/ul/li[@class='_21Ahn-'][3]")
        Primary_Camera.append(pc.text)
        
    except:
        Primary_Camera.append("-")
    ## Fetching Battery Capacity:
    try:
        battery = driver.find_element_by_xpath("//div[@class = '_2418kt']/ul/li[4]")
        Battery_Capacity.append(battery.text)
    except:
        Battery_Capacity.append("-")
        
        


        
        
        
print(len(Brand)) 
print(Brand)

# print(len(Phone_Name)) 
# print(Phone_Name)

print(len(Price)) 
print(Price)


print(len(Rom)) 
#print(Rom)
# for i in Rom:
#     RAM = i.split("|")[0]
#     ROM = i.split("|")[1]
    
#     print(RAM)  
#     print(len(RAM))
#     print(ROM)
#     print(len(ROM))



print(len(Display_Size)) 
print(Display_Size)

print(len(Primary_Camera))
print(Primary_Camera)

print(len(Battery_Capacity))
print(Battery_Capacity)

14
['LAVA Pixel V2 Plus (Black, 16 GB)  (2 GB RAM)', '-', 'ringme Reno Plus (Blue, 16 GB)  (2 GB RAM)', 'ringme Reno Plus (Red, 16 GB)  (2 GB RAM)', 'KARBONN Titanium S9 plus (Blue, 32 GB)  (3 GB RAM)', 'SAMSUNG Galaxy Note 10 Plus (Aura White, 256 GB)  (12 GB RAM)', 'I Kall K38 Plus  (Blue / Light Blue)', 'Phicomm Clue 3 Plus VoLTE (Gold, 16 GB)  (2 GB RAM)', 'Micromax Bharat 4 Plus (Black, 16 GB)  (2 GB RAM)', 'ringme R1 Plus  (Golden)', 'I Kall K 8 NEw / K-8Plus (Red, 16 GB)  (2 GB RAM)', 'Nokia 5.1 Plus (Blue, 64 GB)  (6 GB RAM)', 'ringme R1 Plus  (Blue)', 'Zopo Flash X Plus (Rose Gold, 32 GB)  (3 GB RAM)']
14
['₹6,199', '-', '₹4,999', '₹5,148', '₹5,999', '₹85,000', '₹899', '₹5,509', '₹4,995', '₹995', '₹4,429', '₹11,500', '₹995', '₹4,949']
14
14
['12.7 cm (5 inch) Display', '-', '15.75 cm (6.2 inch) Display', '15.75 cm (6.2 inch) Display', '15.49 cm (6.1 inch) Display', '17.27 cm (6.8 inch) Display', '4.57 cm (1.8 inch) Display', '12.7 cm (5 inch) Display', '12.7 cm (5 inch) Display', '4.57 cm (1.8 inch) Display', '13.97 cm (5.5 inch) Display', '14.73 cm (5.8 inch) Display', '4.57 cm (1.8 inch) Display', '13.97 cm (5.5 inch) Full HD Display']
14
['13MP + 13MP | 5MP + 5MP Dual Front Camera', '-', '8MP Rear Camera', '8MP Rear Camera', '8MP Rear Camera', '12MP (Dual Aperture) + 12MP + 16MP + TOF | 10MP Front Camera', '0.3MP Rear Camera', '8MP Rear Camera', '8MP Rear Camera', '1MP Rear Camera', '5MP Rear Camera', '13MP Rear Camera', '1MP Rear Camera', '13MP Rear Camera | 8MP Front Camera']
14
['2500 mAh Battery', '-', '3000 mAh Battery', '3000 mAh Battery', '3000 mAh Battery', '4300 mAh Battery', '1000 mAh Battery', '3000 mAh Battery', '3000 mAh Battery', '1500 mAh Battery', '2200 mAh Battery', '3060 mAh Battery', '1500 mAh Battery', '3100 mAh Battery']

In [95]:
## making DataFrame:
flipkart_df = pd.DataFrame({'Product': Brand,
                            'Price' : Price,
                            'RAM/ROM' : Rom,
                            'Camera':Primary_Camera,
                            'Battery':Battery_Capacity
                           })
flipkart_df

,Product,Price,RAM/ROM,Camera,Battery
0,"LAVA Pixel V2 Plus (Black, 16 GB) (2 GB RAM)","₹6,199",2 GB RAM | 16 GB ROM,13MP + 13MP | 5MP + 5MP Dual Front Camera,2500 mAh Battery
1,-,-,-,-,-
2,"ringme Reno Plus (Blue, 16 GB) (2 GB RAM)","₹4,999",2 GB RAM | 16 GB ROM,8MP Rear Camera,3000 mAh Battery
3,"ringme Reno Plus (Red, 16 GB) (2 GB RAM)","₹5,148",2 GB RAM | 16 GB ROM,8MP Rear Camera,3000 mAh Battery
4,"KARBONN Titanium S9 plus (Blue, 32 GB) (3 GB ...","₹5,999",3 GB RAM | 32 GB ROM,8MP Rear Camera,3000 mAh Battery
5,"SAMSUNG Galaxy Note 10 Plus (Aura White, 256 G...","₹85,000",12 GB RAM | 256 GB ROM | Expandable Upto 1 TB,12MP (Dual Aperture) + 12MP + 16MP + TOF | 10M...,4300 mAh Battery
6,I Kall K38 Plus (Blue / Light Blue),₹899,32 MB RAM | 64 MB ROM,0.3MP Rear Camera,1000 mAh Battery
7,"Phicomm Clue 3 Plus VoLTE (Gold, 16 GB) (2 GB...","₹5,509",2 GB RAM | 16 GB ROM,8MP Rear Camera,3000 mAh Battery
8,"Micromax Bharat 4 Plus (Black, 16 GB) (2 GB RAM)","₹4,995",2 GB RAM | 16 GB ROM,8MP Rear Camera,3000 mAh Battery
9,ringme R1 Plus (Golden),₹995,1 MB RAM | 8 MB ROM,1MP Rear Camera,1500 mAh Battery
10,"I Kall K 8 NEw / K-8Plus (Red, 16 GB) (2 GB RAM)","₹4,429",2 GB RAM | 16 GB ROM,5MP Rear Camera,2200 mAh Battery
11,"Nokia 5.1 Plus (Blue, 64 GB) (6 GB RAM)","₹11,500",6 GB RAM | 64 GB ROM,13MP Rear Camera,3060 mAh Battery
12,ringme R1 Plus (Blue),₹995,1 MB RAM | 8 MB ROM,1MP Rear Camera,1500 mAh Battery
13,"Zopo Flash X Plus (Rose Gold, 32 GB) (3 GB RAM)","₹4,949",3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,13MP Rear Camera | 8MP Front Camera,3100 mAh Battery

In [96]:
## CSV File
flipkart_df.to_csv("flipkart_df.csv")

In [97]:
driver.close()

Q5.Scrapping Cordinates from Google Map:-

In [98]:
## Connect to the driver:
driver = webdriver.Chrome('/users/pratiksingh/Downloads/chromedriver')

In [99]:
driver.get("https://www.google.com/maps/")

In [100]:
driver.find_element_by_xpath("//input[@class='tactile-searchbox-input']").send_keys("Noida")

In [101]:
driver.find_element_by_xpath("//button[@class='nhb85d-BIqFsb']").click()

In [102]:
url = driver.current_url
print(url)

https://www.google.com/maps/place/Noida,+Uttar+Pradesh/@28.9717116,77.692928,14z/data=!4m5!3m4!1s0x390ce5a43173357b:0x37ffce30c87cc03f!8m2!3d28.5355161!4d77.3910265

In [103]:
x = url.split("/")
print(x)

['https:', '', 'www.google.com', 'maps', 'place', 'Noida,+Uttar+Pradesh', '@28.9717116,77.692928,14z', 'data=!4m5!3m4!1s0x390ce5a43173357b:0x37ffce30c87cc03f!8m2!3d28.5355161!4d77.3910265']

In [104]:
lat=x[6]
print(lat)
type(lat)

@28.9717116,77.692928,14z

str

In [105]:
cordinates = lat.split(",")[:]
print(cordinates)
lati = (cordinates[0])
l = lati.strip("@")
print(l)

print("Lattitude of Noida city  is  :", l)
print("Longitude of Noida city  is : " , cordinates[1])

['@28.9717116', '77.692928', '14z']
28.9717116
Lattitude of Noida city  is  : 28.9717116
Longitude of Noida city  is :  77.692928

In [106]:
driver.close()

Q6.Write a program to scrap details of all the funding deals for second quarter (i.e. July 20 – September 20) from trak.in.

In [107]:
## Connect to the driver:
driver = webdriver.Chrome('/users/pratiksingh/Downloads/chromedriver')
## Getting the url:
driver.get("https://trak.in/")
driver.maximize_window()
## Scrapping Funding Deals :
section = driver.find_element_by_xpath("//li[@class='menu-have-icon menu-icon-type-fontawesome menu-item menu-item-type-post_type menu-item-object-page better-anim-fade menu-item-51510'][1]")
section.click()

In [108]:
### Making Empty lists:-
Date = []
Startup=[]
Industry =[]
Sub_Vertical =[]
City =[]
Investor_Details =[]
Investment_Type =[]
Amount =[]
##Scrapping March data:
march = driver.find_element_by_xpath("//h2[@class='tablepress-table-name tablepress-table-name-id-56']")
print(march.text)

## Scrapping details for Date for March 2021:-
dt = driver.find_elements_by_xpath("//table[@id='tablepress-56']/tbody/tr/td[2]")
for i in dt:
    Date.append(i.text)
print(Date) 

## Scrapping Startup Name for March 2021 data:-
stup= driver.find_elements_by_xpath("//table[@id='tablepress-56']/tbody/tr/td[3]")
for i in stup:
    Startup.append(i.text)
print(Startup) 
##  Scrapping industry details:-
ind = driver.find_elements_by_xpath("//table[@id='tablepress-56']/tbody/tr/td[4]")
for i in ind:
    Industry.append(i.text)
print(Industry)
### Scrapping Sub-Vertical:-
sub_ver = driver.find_elements_by_xpath("//table[@id='tablepress-56']/tbody/tr/td[5]") 
for i in sub_ver:
    Sub_Vertical.append(i.text)
print(Sub_Vertical)

##scrapping City:
city = driver.find_elements_by_xpath("//table[@id='tablepress-56']/tbody/tr/td[6]")
for i in city:
    City.append(i.text)
print(City)    
## Sccrapping Industry Details:
idt = driver.find_elements_by_xpath("//table[@id='tablepress-56']/tbody/tr/td[7]")
for i in idt:
    Investor_Details.append(i.text)
print(Investor_Details)    
## Scrapping Investment Type:
ivt = driver.find_elements_by_xpath("//table[@id='tablepress-56']/tbody/tr/td[8]")
for i in ivt:
    Investment_Type.append(i.text)
print(Investment_Type)  

amt = driver.find_elements_by_xpath("//table[@id='tablepress-56']/tbody/tr/td[9]")
for i in amt:
    Amount.append(i.text)
print(Amount)  
    
### Making Data Frame and CSV for March 2021 Funding deals
March_df = pd.DataFrame({'Date':Date,
                         'StartUp':Startup,
                          'Industry':Industry,
                         'Sub Vertical':Sub_Vertical,
                         'City'      : City,
                         'Investor Details':Investor_Details,
                         'Investment Type':Investment_Type,
                         'Amount':Amount
                         
                       })
print("------March Funding Deals 2021-------")    

    

March_df

March, 2021
['04/03/2021', '31/03/2021', '30/03/2021', '30/03/2021', '23/03/2021', '25/03/2021', '26/03/2021']
['DealShare', 'Uniphore', 'Dunzo', 'BYJU’S', 'SkilloVilla', 'CityMall', 'DotPe']
['E-commerce', 'Technology', 'E-commerce', 'Edu-tech', 'Edu-tech', 'E-commerce', 'FinTech']
['Online shopping platform', 'Conversational Service Automation (CSA)', 'Hyper-local delivery app', 'Online tutoring', 'Career and job-oriented upskilling.', 'Social ecommerce and online grocery platform', 'Commerce and payments platform to offline enterprise businesses.']
['Jaipur, Rajasthan', 'Palo Alto', 'Bengaluru', 'Bengaluru', 'Bengaluru', 'Gurgaon', 'Gurgaon']
['Innoven Capital', 'Sorenson Capital Partners', 'Krishtal Advisors Pte Ltd', 'MC Global Edtech, B Capital, Baron, others', 'Titan Capital, others', 'Accel Partners', 'PayU']
['Debt Financing', 'Series D', 'Series E', 'Series F', 'Seed', 'Series A', 'Series A']
['250,000,000', '140,000,000', '8,000,000', '460,000,000', '300,000,000', '11,000,000', '27,500,000']
------March Funding Deals 2021-------

,Date,StartUp,Industry,Sub Vertical,City,Investor Details,Investment Type,Amount
0,04/03/2021,DealShare,E-commerce,Online shopping platform,"Jaipur, Rajasthan",Innoven Capital,Debt Financing,"250,000,000"
1,31/03/2021,Uniphore,Technology,Conversational Service Automation (CSA),Palo Alto,Sorenson Capital Partners,Series D,"140,000,000"
2,30/03/2021,Dunzo,E-commerce,Hyper-local delivery app,Bengaluru,Krishtal Advisors Pte Ltd,Series E,"8,000,000"
3,30/03/2021,BYJU’S,Edu-tech,Online tutoring,Bengaluru,"MC Global Edtech, B Capital, Baron, others",Series F,"460,000,000"
4,23/03/2021,SkilloVilla,Edu-tech,Career and job-oriented upskilling.,Bengaluru,"Titan Capital, others",Seed,"300,000,000"
5,25/03/2021,CityMall,E-commerce,Social ecommerce and online grocery platform,Gurgaon,Accel Partners,Series A,"11,000,000"
6,26/03/2021,DotPe,FinTech,Commerce and payments platform to offline ente...,Gurgaon,PayU,Series A,"27,500,000"

In [109]:
### Making csv
March_df.to_csv('March_2021_FundingDeals.csv')

In [110]:
### Making Empty lists:-
Date = []
Startup=[]
Industry =[]
Sub_Vertical =[]
City =[]
Investor_Details =[]
Investment_Type =[]
Amount =[]

### Scrapping February Data:-
##Scrapping February data:
feb = driver.find_element_by_xpath("//h2[@class='tablepress-table-name tablepress-table-name-id-55']")
print(feb.text)

## Scrapping details for Date for FEB 2021:-
dt = driver.find_elements_by_xpath("//table[@id='tablepress-55']/tbody/tr/td[2]")
for i in dt:
    Date.append(i.text)
print(Date) 

## Scrapping Startup Name for FEB 2021 data:-
stup= driver.find_elements_by_xpath("//table[@id='tablepress-55']/tbody/tr/td[3]")
for i in stup:
    Startup.append(i.text)
print(Startup) 
##  Scrapping industry details:-
ind = driver.find_elements_by_xpath("//table[@id='tablepress-55']/tbody/tr/td[4]")
for i in ind:
    Industry.append(i.text)
print(Industry)
### Scrapping Sub-Vertical:-
sub_ver = driver.find_elements_by_xpath("//table[@id='tablepress-55']/tbody/tr/td[5]") 
for i in sub_ver:
    Sub_Vertical.append(i.text)
print(Sub_Vertical)

##scrapping City:
city = driver.find_elements_by_xpath("//table[@id='tablepress-55']/tbody/tr/td[6]")
for i in city:
    City.append(i.text)
print(City)    
## Sccrapping Industry Details:
idt = driver.find_elements_by_xpath("//table[@id='tablepress-55']/tbody/tr/td[7]")
for i in idt:
    Investor_Details.append(i.text)
print(Investor_Details)    
## Scrapping Investment Type:
ivt = driver.find_elements_by_xpath("//table[@id='tablepress-55']/tbody/tr/td[8]")
for i in ivt:
    Investment_Type.append(i.text)
print(Investment_Type)  

amt = driver.find_elements_by_xpath("//table[@id='tablepress-55']/tbody/tr/td[9]")
for i in amt:
    Amount.append(i.text)
print(Amount)  
    
### Making Data Frame and CSV for FEB 2021 Funding deals
FEB_df = pd.DataFrame({'Date':Date,
                         'StartUp':Startup,
                          'Industry':Industry,
                         'Sub Vertical':Sub_Vertical,
                         'City'      : City,
                         'Investor Details':Investor_Details,
                         'Investment Type':Investment_Type,
                         'Amount':Amount
                         
                       })
  
print("------February Funding Deals 2021-------")    

FEB_df

February, 2021
['11/02/2021', '22/02/2021', '19/02/2021', '17/02/2021', '15/02/2021', '12/02/2021', '12/02/2021', '09/02/2021', '09/02/2021']
['Doubtnut', 'Zomato', 'Fingerlix', 'Zolve', 'KreditBee', 'Pepperfry', 'Grofers', 'Nothing', 'SplashLearn']
['Edu Tech', 'Hospitality', 'Hospitality', 'FinTech', 'Finance', 'E-commerce', 'E-Commerce', 'Technology', 'EdTech']
['E-Learning Platform', 'Online Food Delivery Platform', 'Semi-cooked food delivery app', 'Global Neobank Venture', 'Digital lending platform', 'Multi-brand furniture brand', 'Online supermarket', 'Consumer Technology Venture', 'Game-based learning programme']
['Gurgaon', 'Gurgaon', 'Mumbai', 'Mumbai', 'Bengaluru', 'Mumbai', 'Gurgaon', 'London', 'Gurgaon']
['SIG Global, Sequoia Capital, WaterBridge Ventures and ON Mauritius', 'Tiger Global, Kora', 'Rhodium Trust, Accel Partners and Swiggy', 'Accel Partners and Lightspeed Venture Partners', 'Azim Premji’s PremjiInvest and South Korea’s Mirae Asset Venture', 'InnoVen Capital', 'SoftBank Vision Fund (SVF)', 'GV', 'Owl Ventures']
['Series B', 'Venture', 'Series C', 'Seed', 'Series C', 'Debt Financing', 'Unspecified', 'Series A', 'Series C']
['2,500,000', '250,000,000', '2,747,045.20', '1,50,00,000', '75,000,000', '4,773,958', '55,000,000', '15,000,000', '18,000,000']
------February Funding Deals 2021-------

,Date,StartUp,Industry,Sub Vertical,City,Investor Details,Investment Type,Amount
0,11/02/2021,Doubtnut,Edu Tech,E-Learning Platform,Gurgaon,"SIG Global, Sequoia Capital, WaterBridge Ventu...",Series B,"2,500,000"
1,22/02/2021,Zomato,Hospitality,Online Food Delivery Platform,Gurgaon,"Tiger Global, Kora",Venture,"250,000,000"
2,19/02/2021,Fingerlix,Hospitality,Semi-cooked food delivery app,Mumbai,"Rhodium Trust, Accel Partners and Swiggy",Series C,"2,747,045.20"
3,17/02/2021,Zolve,FinTech,Global Neobank Venture,Mumbai,Accel Partners and Lightspeed Venture Partners,Seed,"1,50,00,000"
4,15/02/2021,KreditBee,Finance,Digital lending platform,Bengaluru,Azim Premji’s PremjiInvest and South Korea’s M...,Series C,"75,000,000"
5,12/02/2021,Pepperfry,E-commerce,Multi-brand furniture brand,Mumbai,InnoVen Capital,Debt Financing,"4,773,958"
6,12/02/2021,Grofers,E-Commerce,Online supermarket,Gurgaon,SoftBank Vision Fund (SVF),Unspecified,"55,000,000"
7,09/02/2021,Nothing,Technology,Consumer Technology Venture,London,GV,Series A,"15,000,000"
8,09/02/2021,SplashLearn,EdTech,Game-based learning programme,Gurgaon,Owl Ventures,Series C,"18,000,000"

In [111]:
### Making csv
FEB_df.to_csv('FEB_2021_FundingDeals.csv')

In [112]:
### Making Empty lists:-
Date = []
Startup=[]
Industry =[]
Sub_Vertical =[]
City =[]
Investor_Details =[]
Investment_Type =[]
Amount =[]

### Scrapping January Data:-
##Scrapping January data:
feb = driver.find_element_by_xpath("//h2[@class='tablepress-table-name tablepress-table-name-id-54']")
print(feb.text)

## Scrapping details for Date for JAN 2021:-
dt = driver.find_elements_by_xpath("//table[@id='tablepress-54']/tbody/tr/td[2]")
for i in dt:
    Date.append(i.text)
print(Date) 

## Scrapping Startup Name for JAN 2021 data:-
stup= driver.find_elements_by_xpath("//table[@id='tablepress-54']/tbody/tr/td[3]")
for i in stup:
    Startup.append(i.text)
print(Startup) 
##  Scrapping industry details:-
ind = driver.find_elements_by_xpath("//table[@id='tablepress-54']/tbody/tr/td[4]")
for i in ind:
    Industry.append(i.text)
print(Industry)
### Scrapping Sub-Vertical:-
sub_ver = driver.find_elements_by_xpath("//table[@id='tablepress-54']/tbody/tr/td[5]") 
for i in sub_ver:
    Sub_Vertical.append(i.text)
print(Sub_Vertical)

##scrapping City:
city = driver.find_elements_by_xpath("//table[@id='tablepress-54']/tbody/tr/td[6]")
for i in city:
    City.append(i.text)
print(City)    
## Sccrapping Industry Details:
idt = driver.find_elements_by_xpath("//table[@id='tablepress-54']/tbody/tr/td[7]")
for i in idt:
    Investor_Details.append(i.text)
print(Investor_Details)    
## Scrapping Investment Type:
ivt = driver.find_elements_by_xpath("//table[@id='tablepress-54']/tbody/tr/td[8]")
for i in ivt:
    Investment_Type.append(i.text)
print(Investment_Type)  

amt = driver.find_elements_by_xpath("//table[@id='tablepress-54']/tbody/tr/td[9]")
for i in amt:
    Amount.append(i.text)
print(Amount)  
    
### Making Data Frame and CSV for Jan 2021 Funding deals
Jan_df = pd.DataFrame({'Date':Date,
                         'StartUp':Startup,
                          'Industry':Industry,
                         'Sub Vertical':Sub_Vertical,
                         'City'      : City,
                         'Investor Details':Investor_Details,
                         'Investment Type':Investment_Type,
                         'Amount':Amount
                         
                       })
print("------January Funding Deals 2021-------")    

Jan_df

January, 2021
['15/01/2021', '28/01/2021', '19/01/2021', '19/01/2021', '18/01/2021', '18/01/2021', '11/01/2021', '13/01/2021']
['Digit Insurance', 'Bombay Shaving Company', 'DeHaat', 'Darwinbox', 'mfine', 'Udayy', 'True Elements', 'Saveo']
['Financial Services', 'Consumer Goods Company', 'AgriTech Startup', 'SaaS', 'Health Tech Startup', 'EdTech', 'Food Startup', 'B2B E-commerce']
['Insurance Services', 'Shave care, beard care, and skincare products', 'online marketplace for farm products and services', 'HR Tech', 'AI-powered telemedicine mobile app', 'Online learning platform for kids in class 1-5', 'Whole Food plant based Nashta', 'Pharmacies']
['Bengaluru', 'New Delhi', 'Patna', 'Mumbai', 'Bengaluru', 'Gurgaon', 'Pune', 'Bengaluru']
['A91 Partners, Faering Capital, TVS Capital Funds', 'Reckitt Benckiser', 'Prosus Ventures', 'Salesforce Ventures', 'Heritas Capital Management', 'Sequoia Capital', 'SIDBI Venture Capital', 'Matrix Partners India, RTP Global, others']
['Venture', 'Venture', 'Series C', 'Seed', 'Venture Round', 'Seed Funding', 'Series', 'Seed']
['1,80,00,000', '6,172,258.50', '30,000,000', '15,000,000', '16,000,000', '15,000,000', '100,000,000', '4,000,000']
------January Funding Deals 2021-------

,Date,StartUp,Industry,Sub Vertical,City,Investor Details,Investment Type,Amount
0,15/01/2021,Digit Insurance,Financial Services,Insurance Services,Bengaluru,"A91 Partners, Faering Capital, TVS Capital Funds",Venture,"1,80,00,000"
1,28/01/2021,Bombay Shaving Company,Consumer Goods Company,"Shave care, beard care, and skincare products",New Delhi,Reckitt Benckiser,Venture,"6,172,258.50"
2,19/01/2021,DeHaat,AgriTech Startup,online marketplace for farm products and services,Patna,Prosus Ventures,Series C,"30,000,000"
3,19/01/2021,Darwinbox,SaaS,HR Tech,Mumbai,Salesforce Ventures,Seed,"15,000,000"
4,18/01/2021,mfine,Health Tech Startup,AI-powered telemedicine mobile app,Bengaluru,Heritas Capital Management,Venture Round,"16,000,000"
5,18/01/2021,Udayy,EdTech,Online learning platform for kids in class 1-5,Gurgaon,Sequoia Capital,Seed Funding,"15,000,000"
6,11/01/2021,True Elements,Food Startup,Whole Food plant based Nashta,Pune,SIDBI Venture Capital,Series,"100,000,000"
7,13/01/2021,Saveo,B2B E-commerce,Pharmacies,Bengaluru,"Matrix Partners India, RTP Global, others",Seed,"4,000,000"

In [113]:
driver.close()

Q7.Write a program to scrap all the available details of best gaming laptops from digit.in.

In [114]:
## Connect to the driver:
driver = webdriver.Chrome('/users/pratiksingh/Downloads/chromedriver')
## Getting the url:
driver.get("https://www.digit.in/")
driver.maximize_window()
url = driver.find_element_by_xpath("//div[@class='menu']/ul/li[3]")
url.click()
link = driver.find_element_by_xpath("//div[@class='Listbrand']/ul/li[10]")
link.click()

In [115]:
## Making empty lists:

Product_Name=[]
OS =[]
Display=[]
Processor=[]
Memory=[]
Weight=[]
Dimension=[]
Graphics_Processor=[]

## Scrapping Product Name:-
pd_name = driver.find_elements_by_xpath("//div[@class='TopNumbeHeading sticky-footer']/a")
pd_name1 =driver.find_element_by_xpath("//div[@class='TopNumbeHeading sticky-footer active']/a/h3")
print(pd_name1.text)
for i in pd_name:
    Product_Name.append(i.text)
Product_Name.insert(1,pd_name1.text) 
print(Product_Name)
print(len(Product_Name))

## Scrapping OS name:
os_name = driver.find_elements_by_xpath("//div[@class='Spcs-details']/table/tbody/tr[3]/td[3]")
for i in os_name:
    OS.append(i.text)
print(OS) 
print(len(OS))
    
## Scrapping Display:
display = driver.find_elements_by_xpath("//div[@class='Spcs-details']/table/tbody/tr[4]/td[3]")
for i in display:
    Display.append(i.text)
print(Display) 
print(len(Display))

## Scrapping Processor:-
processor = driver.find_elements_by_xpath("//div[@class='Spcs-details']/table/tbody/tr[5]/td[3]")
for i in processor:
    Processor.append(i.text)
print(Processor) 
print(len(Processor))

## Scrapping Memory:
memory = driver.find_elements_by_xpath("//div[@class='Spcs-details']/table/tbody/tr[6]/td[3]")
for i in memory:
    Memory.append(i.text)
print(Memory) 
print(len(Memory))

## Scrapping Weight:
weight = driver.find_elements_by_xpath("//div[@class='Spcs-details']/table/tbody/tr[7]/td[3]")
for i in weight:
    Weight.append(i.text)
print(Weight) 
print(len(Weight))

## Scrapping Dimension:
dim =driver.find_elements_by_xpath("//div[@class='Spcs-details']/table/tbody/tr[8]/td[3]")
for i in dim:
    Dimension.append(i.text)
print(Dimension) 
print(len(Dimension))

## Scrapping Graphics Processor:
gp =driver.find_elements_by_xpath("//div[@class='Spcs-details']/table/tbody/tr[9]/td[3]")
for i in gp:
    Graphics_Processor.append(i.text)
print(Graphics_Processor) 
print(len(Graphics_Processor))

ACER NITRO 5
['HP VICTUS 16', 'ACER NITRO 5', 'HP OMEN 15', 'MSI STEALTH 15M', 'ASUS ROG STRIX SCAR 15', 'ASUS ROG STRIX SCAR 15', 'ASUS ZEPHYRUS G14', 'LENOVO LEGION 5I', 'ASUS ROG ZEPHYRUS DUO 15', 'ACER ASPIRE 7 GAMING LAPTOP']
10
['Windows 10', 'Windows 10 Home', 'Windows 10', 'Windows 10', 'Windows 10', 'Windows 10 Home', 'Windows 10 Home', 'Windows 10 Pro', 'Windows 10', 'Windows 10 Home']
10
['16.1" (1920 x 1200)', '15.6" (1920 x 1080)', '15.6" (1920 x 1080)', '15.6" (1920 x 1080)', '15.6" (2560 x 1440)', '15.6" (1920 x 1080)', '14" (1920 x 1080)', '15.6" (1920 x 1080)', '15.6" (3840 x 1100)', '15.6" (1920 x 1080)']
10
['5th Gen AMD Ryzen 7 5800H | 3.2GHz', 'AMD Ryzen 7 Octa Core-5800H | 4.4 GHz', 'AMD Ryzen 9 Octa Core | 2.4 GHz', 'Intel Core i7 11th Gen - 11375H | NA', 'AMD Ryzen 9 Octa Core - 5900HX | 3.3 GHz', 'AMD Ryzen™ 9 5900HX | 3.3 GHz', 'AMD 3rd Gen Ryzen 9 | 3.3 GHz', '10th Gen Intel® Core™ i5-10300H | 2.50 GHz', 'Intel Core i7 10th Gen 10875H | NA', 'AMD Ryzen™ 5-5500U hexa-core | NA']
10
['512 GB SSD/16 GBGB DDR4', '1 TB SSD/16 GBGB DDR4', '1 TB HDD/16 GBGB DDR4', '1 TB SSD/16 GBGB DDR4', '2 TB SSD/32 GBGB DDR4', '1 TB SSD/16 GBGB DDR4', '1 TB SSD/16 GBGB DDR4', '1 TB SSD/16 GBGB DDR4', '512 GB SSD/4 GBGB DDR4', '512 GB SSD/8 GBGB DDR4']
10
['2.48', '2.37', '2.4', '1.7', '2.30', '2.30', '1.65', '2.3', '2.4', '2.15']
10
['37 x 26.2 x 2.4', '357.9 x 239.7 x 22.5', '363.4 x 255 x 23.9', '358.3 x 248 x 16.15', '354 x 259 x 22.6', '35.4 x 25.9 x 2.26', '32.5 x 22.1 x 1.8', '363.06 x 259.61 x 23.57', '268.30 x 360.00 x 20.90', '2.29 x 36.3 x 25.4']
10
['NVIDIA GeForce RTX 3060', 'NVIDIA GeForce RTX 3060', 'NVIDIA GeForce RTX 3070', 'NVIDIA GeForce RTX 3060', 'NVIDIA GeForce RTX 3080', 'NVIDIA® GeForce RTX™ 3070', 'NVIDIA GeForce RTX 2060', 'NVIDIA® GeForce® GTX 1650 4GB', 'NVIDIA GeForce RTX 2070 Max-Q', 'NVIDIA® GeForce® GTX 1650']
10

In [116]:
## Making DataFrame:
gaming_laptop = pd.DataFrame({ 'Name':Product_Name,
                              'OS' :OS,
                              'Display':Display,
                              'Processor':Processor,
                              'Memory':Memory,
                              'Weight':Weight,
                              'Dimensions':Dimension,
                              'Graphic Processor':Graphics_Processor
    
                             })

gaming_laptop

,Name,OS,Display,Processor,Memory,Weight,Dimensions,Graphic Processor
0,HP VICTUS 16,Windows 10,"16.1"" (1920 x 1200)",5th Gen AMD Ryzen 7 5800H | 3.2GHz,512 GB SSD/16 GBGB DDR4,2.48,37 x 26.2 x 2.4,NVIDIA GeForce RTX 3060
1,ACER NITRO 5,Windows 10 Home,"15.6"" (1920 x 1080)",AMD Ryzen 7 Octa Core-5800H | 4.4 GHz,1 TB SSD/16 GBGB DDR4,2.37,357.9 x 239.7 x 22.5,NVIDIA GeForce RTX 3060
2,HP OMEN 15,Windows 10,"15.6"" (1920 x 1080)",AMD Ryzen 9 Octa Core | 2.4 GHz,1 TB HDD/16 GBGB DDR4,2.4,363.4 x 255 x 23.9,NVIDIA GeForce RTX 3070
3,MSI STEALTH 15M,Windows 10,"15.6"" (1920 x 1080)",Intel Core i7 11th Gen - 11375H | NA,1 TB SSD/16 GBGB DDR4,1.7,358.3 x 248 x 16.15,NVIDIA GeForce RTX 3060
4,ASUS ROG STRIX SCAR 15,Windows 10,"15.6"" (2560 x 1440)",AMD Ryzen 9 Octa Core - 5900HX | 3.3 GHz,2 TB SSD/32 GBGB DDR4,2.30,354 x 259 x 22.6,NVIDIA GeForce RTX 3080
5,ASUS ROG STRIX SCAR 15,Windows 10 Home,"15.6"" (1920 x 1080)",AMD Ryzen™ 9 5900HX | 3.3 GHz,1 TB SSD/16 GBGB DDR4,2.30,35.4 x 25.9 x 2.26,NVIDIA® GeForce RTX™ 3070
6,ASUS ZEPHYRUS G14,Windows 10 Home,"14"" (1920 x 1080)",AMD 3rd Gen Ryzen 9 | 3.3 GHz,1 TB SSD/16 GBGB DDR4,1.65,32.5 x 22.1 x 1.8,NVIDIA GeForce RTX 2060
7,LENOVO LEGION 5I,Windows 10 Pro,"15.6"" (1920 x 1080)",10th Gen Intel® Core™ i5-10300H | 2.50 GHz,1 TB SSD/16 GBGB DDR4,2.3,363.06 x 259.61 x 23.57,NVIDIA® GeForce® GTX 1650 4GB
8,ASUS ROG ZEPHYRUS DUO 15,Windows 10,"15.6"" (3840 x 1100)",Intel Core i7 10th Gen 10875H | NA,512 GB SSD/4 GBGB DDR4,2.4,268.30 x 360.00 x 20.90,NVIDIA GeForce RTX 2070 Max-Q
9,ACER ASPIRE 7 GAMING LAPTOP,Windows 10 Home,"15.6"" (1920 x 1080)",AMD Ryzen™ 5-5500U hexa-core | NA,512 GB SSD/8 GBGB DDR4,2.15,2.29 x 36.3 x 25.4,NVIDIA® GeForce® GTX 1650

In [117]:
##  making csv file:
gaming_laptop.to_csv('best_gaming_laptop.csv')
## Closing driver
driver.close()

Q8.Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [118]:
## Connect to the driver:
driver = webdriver.Chrome('/users/pratiksingh/Downloads/chromedriver')

## Getting the url:
driver.maximize_window()
driver.get("https://www.forbes.com/billionaires/")

In [119]:
# empty list
Rank = []
Name = []
Net_worth = []
Age = []
Citizenship = []
Source = []
Industry = []

In [120]:
# extracting the rank
rank = driver.find_elements_by_xpath("//div[@class='rank']")
for i in rank:
    Rank.append(i.text)

# extracting the name
name = driver.find_elements_by_xpath("//div[@class='personName']")
for i in name:
    Name.append(i.text)

# extracting the net worth 
nw= driver.find_elements_by_xpath("//div[@class='netWorth']")
for i in nw:
    Net_worth.append(i.text)

# extracting the age
age = driver.find_elements_by_xpath("//div[@class='age']")
for i in age:
    Age.append(i.text)

# extracting the citizenship
citizen = driver.find_elements_by_xpath("//div[@class='countryOfCitizenship']")
for i in citizen:
    Citizenship.append(i.text)

# extracting the source
src = driver.find_elements_by_xpath("//div[@class='source']")
for i in src:
    Source.append(i.text)

# extracting the industry
ind = driver.find_elements_by_xpath("//div[@class='category']")
for i in ind:
    Industry.append(i.text)

In [121]:
# creating data frame
df = pd.DataFrame({})
df['Rank'] = Rank
df['Name'] = Name
df['Net_worth'] = Net_worth
df['Age'] = Age
df['Citizenship'] = Citizenship
df['Source'] = Source
df['Industry'] = Industry
df

,Rank,Name,Net_worth,Age,Citizenship,Source,Industry
0,1.,Jeff Bezos,$177 B,57,United States,Amazon,Technology
1,2.,Elon Musk,$151 B,49,United States,"Tesla, SpaceX",Automotive
2,3.,Bernard Arnault & family,$150 B,72,France,LVMH,Fashion & Retail
3,4.,Bill Gates,$124 B,65,United States,Microsoft,Technology
4,5.,Mark Zuckerberg,$97 B,36,United States,Facebook,Technology
...,...,...,...,...,...,...,...
195,195.,Harry Triguboff,$11.2 B,88,Australia,real estate,Real Estate
196,197.,Leonid Fedun & family,$11.1 B,65,Russia,oil,Energy
197,197.,Eyal Ofer,$11.1 B,70,Israel,"real estate, shipping",Diversified
198,197.,Evan Spiegel,$11.1 B,30,United States,Snapchat,Technology
199,200.,Luis Carlos Sarmiento,$11 B,88,Colombia,banking,Finance & Investments

Q9.Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [126]:
## Connect to the driver:
driver = webdriver.Chrome('/users/pratiksingh/Downloads/chromedriver')

## Getting url:
driver.get("https://www.youtube.com/")

driver.maximize_window()

# inserting data as per the required job key:
search = driver.find_element_by_xpath("//input[@id='search']")
search.send_keys('gaming channels')
time.sleep(2)
# click on desired video
search = driver.find_element_by_xpath("//*[@id='search-icon-legacy']").click()

In [127]:
href = []
lnks1=driver.find_elements_by_xpath("/html/body/ytd-app/div/ytd-page-manager/ytd-search/div[1]/ytd-two-column-search-results-renderer/div/ytd-section-list-renderer/div[2]/ytd-item-section-renderer/div[3]/ytd-video-renderer[2]/div[1]/div/div[1]/div/h3/a")
for lnk in lnks1:
    href.append(lnk.get_attribute('href'))
print(href)

['https://www.youtube.com/watch?v=8K8kAlC6SHo']

In [129]:
# empty list
comments = []
comment_upvote = []
Time = []

# auto scroll page
SCROLL_PAUSE_TIME = 2
CYCLES = 60

for i in href:
    driver.get(i)
    time.sleep(SCROLL_PAUSE_TIME)
    for i in range(CYCLES):
        html = driver.find_element_by_tag_name('html')
        driver.find_element_by_tag_name('html')
        
        time.sleep(SCROLL_PAUSE_TIME)
   
    
    # scraping the data
    try:
        cmnt = driver.find_elements_by_xpath("//*[@id='content-text']")
        for i in cmnt[0:500]:
            comments.append(i.text)
    except NoSuchElementException:
            comments.append('-')

    try:
        upvote = driver.find_elements_by_xpath("//*[@id='vote-count-middle']")
        for i in upvote[0:500]:
            comment_upvote.append(i.text)
    except NoSuchElementException:
            comment_upvote.append("-")
        

    try:
        time =  driver.find_elements_by_xpath("//*[@id='header-author']/yt-formatted-string/a")
        for i in time[0:500]:
            Time.append(i.text)
    except NoSuchElementException:
            Time.append('-')

In [ ]:
# creating data frame
df = pd.DataFrame({})
df['comments'] = comments
df['comment_upvote'] = comment_upvote
df['Time'] = Time
df

In [144]:
driver.close()

In [145]:
from requests import get
from bs4 import BeautifulSoup

import pandas as pd
import numpy as np

import time

import re

In [164]:
## Connect to the driver:
driver = webdriver.Chrome('/users/pratiksingh/Downloads/chromedriver')

url = "https://www.hostelworld.com/pwa/wds"
driver.get(url)

In [ ]:
searchbtn=driver.find_element_by_xpath("//input[@class='location-text']")
searchbtn.click()

In [150]:
searchjob=driver.find_element_by_xpath("//input[@id='search-input-field']")
searchjob.send_keys('London')

In [151]:
searcbtn=driver.find_element_by_xpath("//ul[@id='predicted-search-results']/li[2]/div")
searcbtn.click()

In [152]:
gobtn=driver.find_element_by_xpath("//button[@id='search-button']")
gobtn.click()

In [ ]:
urls=[]
for i in driver.find_elements_by_xpath("//h2[@class='title title-6']/a"):
    urls.append(i.get_attribute('href'))
urls

In [ ]:
name=[]
distances=[]
ratingss=[]
treviews=[]
oreview=[]
privatepric=[]
dormprice=[]
facilities=[]
descriptions=[]

In [ ]:
#description
for i in urls:
    driver.get(i)
    time.sleep(0.1)
    try:
        des=driver.find_element_by_xpath("//div[@class='flex-80']/div[2]/div/div[2]")
        descriptions.append(des.text)
    except:
        descriptions.append('-')

In [ ]:
descriptions[0:30]

In [ ]:
url='https://www.hostelworld.com/s?q=London,%20England&country=England&city=London&type=city&id=3&from=2021-10-26&to=2021-10-29&guests=2&page=1'

In [ ]:
driver.get(url)

In [ ]:
#name
n=driver.find_elements_by_xpath("//h2[@class='title title-6']")
n[0:30]
for i in n:
    na=i.text
    name.append(na)
name[0:30]

#distances
di=driver.find_elements_by_xpath("//a[@class='show-on-map']/span[1]")
di[0:30]
for i in di:
    dis=i.text
    distances.append(dis)
distances[0:30]

#ratingss
raa=driver.find_elements_by_xpath("//div[@class='rating rating-summary-container big']/div[1]")
raa[0:30]
for i in raa:
    raat=i.text
    ratingss.append(raat)
ratingss[0:30]

#treviews
tr=driver.find_elements_by_xpath("//div[@class='rating rating-summary-container big']/div[2]/div[2]")
tr[0:30]
for i in tr:
    tri=i.text
    treviews.append(tri)
treviews[0:30]

#oreviews
ori=driver.find_elements_by_xpath("//div[@class='rating rating-summary-container big']/div[2]/div[1]/span")
ori[0:30]
for i in ori:
    oriv=i.text
    oreview.append(oriv)
oreview[0:30]

#privateprices
prti=driver.find_elements_by_xpath("//a[@class='prices']/div[1]/div")
prti[0:30]
for i in prti:
    prttt=i.text
    privatepric.append(prttt)
privatepric[0:30]

#dormprice
drti=driver.find_elements_by_xpath("//a[@class='prices']/div[2]/div")
drti[0:30]
for i in drti:
    drttt=i.text
    dormprice.append(drttt)
dormprice[0:30]

#facilities
fac=driver.find_elements_by_xpath("//div[@class='rating-factors prop-card-tablet rating-factors small']")
fac[0:30]
for i in fac:
    faci=i.text
    facilities.append(faci)
facilities[0:30]

In [ ]:
print(len(descriptions[0:30]))
print(len(name[0:30]))
print(len(distances[0:30]))
print(len(ratingss[0:30]))
print(len(treviews[0:30]))
print(len(oreview[0:30]))
print(len(privatepric[0:30]))
print(len(dormprice[0:30]))
print(len(facilities[0:30]))

In [ ]:
hostel=pd.DataFrame({})
hostel['name']=name[0:30]
hostel['distance']=distances[0:30]
hostel['ratings']=ratingss[0:30]
hostel['total']=treviews[0:30]
hostel['overall']=oreview[0:30]
hostel['private']=privatepric[0:30]
hostel['dorm']=dormprice[0:30]
hostel['facilities']=facilities[0:30]
hostel['description']=descriptions[0:30]
hostel